services:
  storage:
   image: redis
   volumes:
    - ./data:/data
  counter:
    image: node:alpine
    volumes:
      - ./:/app
    environment:
     - PORT=3002
     - REDIS_URL=redis://storage
    ports:
      - 80:3002
    working_dir: /app
    command: npm run start
    depends_on:
      - storage