services:
  counter:
    image: node:alpine
    environment:
      - PORT=4000
      - REDIS_URL=redis://storage
    ports:
      - 4000:4000
    working_dir: /app2
    volumes:
      - ./service_counter/:/app2
    command: npm run start
    depends_on:
      - storage

  storage:
    image: redis
    volumes:
      - ./data:/data

  server:
    image: node:alpine
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb://root:example@mongo:27017/
    ports:
      - 80:3000
    working_dir: /app1
    volumes:
      - ./service_book/:/app1
    depends_on:
      - storage
    command: npm run start

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/